services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy

  freqtrade-long:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-long
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8001:8000"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_long.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_long.sqlite
      --config /freqtrade/user_data/config_long.json
      --strategy DcaTpLong

  freqtrade-short:
    image: freqtradeorg/freqtrade:stable

    restart: unless-stopped
    container_name: freqtrade-short
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8002:8000"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_short.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_short.sqlite
      --config /freqtrade/user_data/config_short.json
      --strategy DcaTpShort
